left_frame:
    username:   "Username"
    source:     "{{own}}"
    author:     "Author"
    categories: "July 2022 in Ain|2022 in Montluel"
    license:    "{{self|cc-zero}"
    language:   "fr"

right_frame:
    default_image_sort:   "file_name"

